### PR TITLE
Frozen-Flask for static site generation

### PR DESCRIPTION
**Pull request by eyeseast**
This branch swaps out most of Tarbell's existing static generation code for simple wrappers around [Frozen-Flask](http://pythonhosted.org/Frozen-Flask/). When a new `TarbellSite` is created, a `Freezer` instance is attached to the site and its underlying Flask app, and it sets a few defaults. Calling `tarbell generate` uses [`frozen_flask.walk_directory`](http://pythonhosted.org/Frozen-Flask/#flask_frozen.walk_directory) to find files (and anything linked with `url_for` will be found automatically) and runs `site.freezer.freeze()`.

This is very early in the implementation (written on a plane) and not ready for merging yet, but I want to get feedback early. A few questions up front:

 - **Should there be a default build directory?** Current code creates a temporary directory when you don't specify a destination (`tarbell generate` with no args). This gets used in `tarbell publish`, where Tarbell assumes you don't need the built files locally. (I fixed the `TypeError` in #289). I'm inclined to default to `_site`, both out of habit from using Jekyll and because it's already ignored. 

 - **What hooks do we need?** I can already see a need for a `pre_generate` hook to let you register [URL generators](http://pythonhosted.org/Frozen-Flask/#url-generators) before building. What else?

 - **What does this break?** I'm testing this on my fork of [tarbell.io](http://tarbell.io) and will try a few other sites I have. Would appreciate more testing.

### CODE REVIEW

**Comment by eyeseast** [comment]
Update on this, after a bunch of work over the weekend: This is working, maintaining all current functionality with a lot less code. 

I moved the `generate` hook inside [`TarbellSite.generate_static_site`](https://github.com/eyeseast/tarbell/blob/c9e5433e411af51703a93583711bb17a14c12aa6/tarbell/app.py#L648) and before the actual generation happens. This change will let you register [URL generators](http://pythonhosted.org/Frozen-Flask/#url-generators) before the site gets built. I also slightly changed the signature, making the third argument `extra_context` instead of quiet.

I'm not changing the default build directory yet. Need some feedback on that. Right now, running `tarbell generate` does exactly what it always has, with or without arguments. My inclination is still to default to `_site`, maybe even when running publish, so it's easy to see the built files, but I'd like other opinions before I change current functionality.

I'm testing this on a couple sites: my fork of tarbell.io, Frontline's Ebola map (on a staging server) and a current project. I'll report back after I've used it in production.

Please try this with your own projects and let me know what's buggy, and what's harder than it should be.

**Comment by eads** [comment]
Huzzah!!!

On Mon, Mar 23, 2015 at 2:53 PM, Chris Amico <notifications@github.com>
wrote:

> Update on this, after a bunch of work over the weekend: This is working,
> maintaining all current functionality with a lot less code.
>
> I moved the generate hook inside TarbellSite.generate_static_site
> <https://github.com/eyeseast/tarbell/blob/c9e5433e411af51703a93583711bb17a14c12aa6/tarbell/app.py#L648>
> and before the actual generation happens. This change will let you register URL
> generators <http://pythonhosted.org/Frozen-Flask/#url-generators> before
> the site gets built. I also slightly changed the signature, making the
> third argument extra_context instead of quiet.
>
> I'm not changing the default build directory yet. Need some feedback on
> that. Right now, running tarbell generate does exactly what it always
> has, with or without arguments. My inclination is still to default to
> _site, maybe even when running publish, so it's easy to see the built
> files, but I'd like other opinions before I change current functionality.
>
> I'm testing this on a couple sites: my fork of tarbell.io, Frontline's
> Ebola map (on a staging server) and a current project. I'll report back
> after I've used it in production.
>
> Please try this with your own projects and let me know what's buggy, and
> what's harder than it should be.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/pull/300#issuecomment-85143030>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eyeseast** [comment]
Current version is missing my `css/base.css` file when it's not copied out of the blueprint, possibly because it's never referenced with `url_for` (just included on the page as a relative path). I think I need to find all files within the blueprint, and then find files in the project path. The generator just needs to return paths, so that should be ok.

**Comment by eyeseast** [comment]
Used in production for the app embedded here: http://www.pbs.org/wgbh/pages/frontline/foreign-affairs-defense/frontline-fight-for-yemen/whos-who-in-the-fight-for-yemen/

I have a bigger project in the works that's using custom routes more extensively, but I'm feeling good about this approach.

Anyone want to give this a code review and see what else it needs to be merge-ready?

**Comment by eyeseast** [comment]
Ran into a weird thing today where `FREEZER_RELATIVE_URLS` didn't appear to be working despite being set [here](https://github.com/eyeseast/tarbell/blob/frozen-flask/tarbell/app.py#L284). Need to figure out if that's an actual problem or just my code.

**Comment by eyeseast** [comment]
Last step, I think, is a little documentation explaining what's happening under the hood and where the hooks are. Two places that need updating: [publishing](http://tarbell.readthedocs.org/en/1.0.1/publish.html) and [hooks](http://tarbell.readthedocs.org/en/1.0.1/hooks.html). This update takes away most of the pain of using custom routes, so we can simplify the docs on that, too.

**Comment by eads** [comment]
I'm not sure how to switch the PR branch, but this is now on 1.0.2 and will be in the next release. Thanks so much @eyeseast, this is rad.

**Pull request closed without merging**
