### PR TITLE
Tarbell settings admin

### PR DESCRIPTION
**Pull request by hbillings**
Introduces a `tarbell admin` command that runs a server on `:5001`. This initial version can manage the settings and configuration for S3 and Google.

### CODE REVIEW

**Comment by eads** [comment]
Helloooooo

On Tue, Jul 7, 2015 at 2:26 PM, Heather Billings <notifications@github.com>
wrote:

> Introduces a tarbell admin command that runs a server on :5001. This
> initial version can manage the settings and configuration for S3 and Google.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/tarbell-project/tarbell/pull/344
> Commit Summary
>
>    - Add missing dateutil and datetime imports
>    - Add admin command, basic gui for listing blueprints/projects and
>    running projects
>    - Add settings tab skeleton
>    - Add development doc
>    - Update DEVELOPMENT.md
>    - Add initial admin GUI site
>    - Merge branch 'master' of https://github.com/NUKnightLab/tarbell
>    - Fix initial run modal state
>    - Handle case where preview server starts with non-200 response code
>    - Fix default blueprints; re-generate project/blueprint lists after
>    saving config; info alert if no projects/blueprints
>    - Fix client secrets copy
>    - Add expanduser() before listing projects in projects directory
>    - Change parameter name to avoid conflict with function name (backup)
>    - Fix settings.config clobber in gui.google_auth_secrets
>    - delete blueprint & project management code #24
>    - delete blueprint & project management code #24
>    - Change 'Access Key' to 'Access Key ID' in
>    labels/messages/placeholders
>    - Ditch config modal
>    - Fix "value" attribute
>    - Remove old/unused aria-describedby attributes
>    - more admin styling
>    - fix merge conflix
>    - lots of admin refactoring and restyling
>    - make fields save info after removing checkboxes
>    - move inline JS to admin.js, closes #32
>    - streamline reauthentication workflow; closes #39
>    - add the error messages back in
>    - reintroduce success messages
>    - remove all unnecessary files
>    - add tarbell settings admin
>
> File Changes
>
>    - *A* DEVELOPMENT.md
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-0>
>    (24)
>    - *A* tarbell/admin.py
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-1>
>    (131)
>    - *M* tarbell/app.py
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-2> (2)
>    - *M* tarbell/cli.py
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-3>
>    (20)
>    - *A* tarbell/gui.py
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-4>
>    (174)
>    - *A* tarbell/static/bootstrap-3.3.2-dist/css/bootstrap.min.css
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-5> (5)
>    - *A* tarbell/static/bootstrap-3.3.2-dist/js/bootstrap.min.js
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-6> (7)
>    - *A* tarbell/static/css/admin.css
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-7>
>    (270)
>    - *A* tarbell/static/font-awesome-4.3.0/css/font-awesome.min.css
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-8> (4)
>    - *A* tarbell/static/font-awesome-4.3.0/fonts/FontAwesome.otf
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-9> (0)
>    - *A* tarbell/static/font-awesome-4.3.0/fonts/fontawesome-webfont.eot
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-10>
>    (0)
>    - *A* tarbell/static/font-awesome-4.3.0/fonts/fontawesome-webfont.svg
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-11>
>    (565)
>    - *A* tarbell/static/font-awesome-4.3.0/fonts/fontawesome-webfont.ttf
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-12>
>    (0)
>    - *A* tarbell/static/font-awesome-4.3.0/fonts/fontawesome-webfont.woff
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-13>
>    (0)
>    - *A* tarbell/static/font-awesome-4.3.0/fonts/fontawesome-webfont.woff2
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-14>
>    (0)
>    - *A* tarbell/static/img/ida-logo-full-name.png
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-15>
>    (0)
>    - *A* tarbell/static/img/ida-logo-last-name.png
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-16>
>    (0)
>    - *A* tarbell/static/img/ida-logo.png
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-17>
>    (0)
>    - *A* tarbell/static/img/ida-tarbell.jpg
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-18>
>    (0)
>    - *A* tarbell/static/img/tarbell-logo.png
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-19>
>    (0)
>    - *A* tarbell/static/js/admin-modal.js
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-20>
>    (98)
>    - *A* tarbell/static/js/admin-util.js
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-21>
>    (73)
>    - *A* tarbell/static/js/admin.js
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-22>
>    (407)
>    - *A* tarbell/static/js/jquery-1.10.2.min.js
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-23>
>    (6)
>    - *A* tarbell/static/js/json2.js
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-24>
>    (489)
>    - *A* tarbell/static/js/underscore-1.8.2.min.js
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-25>
>    (5)
>    - *A* tarbell/templates/_blueprints.html
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-26>
>    (15)
>    - *A* tarbell/templates/_projects.html
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-27>
>    (14)
>    - *A* tarbell/templates/_settings.html
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-28>
>    (101)
>    - *A* tarbell/templates/admin.html
>    <https://github.com/tarbell-project/tarbell/pull/344/files#diff-29>
>    (142)
>
> Patch Links:
>
>    - https://github.com/tarbell-project/tarbell/pull/344.patch
>    - https://github.com/tarbell-project/tarbell/pull/344.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/pull/344>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by JoeGermuska** [comment]
👍

**Comment by eads** [comment]
Okay! I finally reviewed this in depth. It's really slick and good progress and I suspect we can get this into a release in the next few weeks. Lots of stuff to note:

* The link in the "static websites for story tellers" to http://tarbell.io is missing the http:// bit. But does that need to be a link at all?
* The overall flow of the form is a bit odd, particularly the way the default project path is grouped with the page header. 
* I like having a note about Ida, but I'm worried it's noise.
* The save button gets a little lost -- does it make sense to autosave? I can see some downsides to that, but it could help with the UX.

As far as form flow, I wonder if each section couldn't be full width, with columns when appropriate. So, with the Google section:

    Accounts with access | Oauth

I dunno -- it's a thought.

**Comment by hbillings** [comment]
Heyo, just circling back around to this (sorry). Are these things that should be addressed prior to merging the pull request? 

I will say I tried the forms a bunch of different ways, and full width feels very...floaty, for lack of a better term. It also makes the settings seem like an overwhelming list because they take up so much space. I'm sure I (or the community) can do better than what I threw together in eight hours, though.

**Comment by eads** [comment]
Sorry for the late reply. Let's integrate it and iterate on the design :dancer:

**Comment by hbillings** [comment]
Whoo!! Should I try to merge it into the new version and submit a new PR?

**Comment by eyeseast** [comment]
Didn't actually mean to close this. Sorry. Leaving it open until @hbillings says otherwise.

**Comment by eyeseast** [comment]
Since this hasn't been touched in a long, long time, does anyone object if I close it?

@hbillings @eads @JoeGermuska

**Comment by eyeseast** [comment]
Seeing no objections, I'm going to close this for now. Happy to reopen if someone wants to take up the cause again.

**Pull request closed without merging**
