### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by myersjustinc**
Was in one of the many "why are/aren't people using Python 3" discussions recently, and heard Tarbell could be a blocker for some hoping to make the move.

So here's my attempt at adding Python 3 support, since a lot's changed since #170. I haven't done a lot with Tarbell myself before this, so I'll definitely want more regular users to kick the tires on this one.

I've tested the following commands under 2.7.13 and 3.5.2, since those are what I just happened to have installed at home:

*   `configure`
*   `generate`
*   `install-blueprint`
*   `newproject`
*   `publish`
*   `serve`
*   `switch`

The proposed tests from #434 also are green under the aforementioned Python versions. (I know it's tagged as a WIP, but it still was helpful when I was getting started.)

I'll also be adding an accompanying PR this afternoon for [tarbell-template](https://github.com/tarbell-project/tarbell-template), since that also needed a couple of tweaks.

### CODE REVIEW

**Comment by eyeseast** [comment]
Thank you! This is amazing. Will look through these changes today. And I should get the test suite merged, since that'll help with this.

**Comment by eyeseast** [comment]
Taking a deeper look at this now that #434 is merged. Looks like `.travis.yml` is still only running tests in `2.7`, so we should update that. I think whatever versions Flask targets are probably reasonable.

**Comment by myersjustinc** [comment]
Good call. [Flask targets 3.3 through 3.6](https://github.com/pallets/flask/blob/7c510199850957161240f081359e2246d8982be1/.travis.yml), so I'll add those this afternoon.

**Comment by myersjustinc** [comment]
Rebased (after your #434 merge) and added those Python versions to `.travis.yml`.

**Comment by eyeseast** [comment]
This might be ready to merge. @myersjustinc any last things you think we should try to work in?

**Comment by myersjustinc** [comment]
Nothing else comes to mind, as long as you think tarbell-project/tarbell-template#15 is ready to go, too.

**Pull request merged**
